# Generated by Django 4.1.1 on 2023-03-01 17:30

import bookingapp.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, validators=[bookingapp.models.validate_pier_check])),
            ],
        ),
        migrations.CreateModel(
            name='BookingPier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pier_status', models.CharField(choices=[("<span class='bk'>бронь</span>", 'бронь'), ("<span class='fr'>вільний</span>", 'вільний')], default='бронь', max_length=40, verbose_name='Стан пірсу')),
                ('time_booking_start', models.DateTimeField(blank=True, null=True, validators=[bookingapp.models.validate_past_time], verbose_name='Прибуття')),
                ('time_booking_finish', models.DateTimeField(blank=True, null=True, validators=[bookingapp.models.validate_past_time], verbose_name='Відбуття')),
                ('wish', models.CharField(max_length=255, validators=[bookingapp.models.validate_wish], verbose_name='Побажання')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Час створення')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Час публікації')),
                ('is_published', models.BooleanField(default=True, verbose_name='Підтверджую бронювання')),
                ('pier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='bookingapp.pier', verbose_name='Пірс')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Користувач')),
            ],
        ),
    ]
